### ISSUE TITLE
Support legacy Python 2.6/3.3/3.4 for python-future

### ISSUE THREAD

**Issue by sfdye** [actions/setup-python#102]
**Describe the bug**

We are thinking of porting https://github.com/PythonCharmers/python-future from Travis to Github Action, however we noticed `python2.6` was not listed in:
https://raw.githubusercontent.com/actions/python-versions/master/versions-manifest.json

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`

**Environment**
- [x] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Python Versions**

2.6.X

**Run/Repo Url**
https://github.com/sfdye/python26-test
https://github.com/sfdye/python26-test/runs/769263785?check_suite_focus=true

**Additional context**

I understand python2.6 is already EOL long time ago, but `future` is compatible layer to ease the migration from Python 2 to Python 3, so the use case still makes sense.

**Comment by konradpabjan** [comment]
Hi @sfdye 

We've published Python `2.6.9` to `actions/python-versions`: https://github.com/actions/python-versions/blob/1cb5ff2fb053a5513ba297d229ab9737b10efba3/versions-manifest.json#L829

We were going to not support this as `2.6.9` is very very old however we quickly tried compiling it with our existing scripts and it worked (exit code 0). Some tests however did fail  (some modules failed to build) but we figured we can publish it anyway as it might work and the certain modules might just be an issue with our tests.

A word of caution though that I have no idea if everything is working correctly and there will be no support if certain things aren't working correctly. If it ends up being totally busted then we can remove it from `python-versions`, but it's worth at least trying since it compiled successfully.

**Comment by sfdye** [comment]
Thank you so much! It's a good start, my test build is green now:
 https://github.com/sfdye/python26-test/runs/877857052?check_suite_focus=true 

I can start migrating to Github Action for `python-future`.

**Comment by sfdye** [comment]
Sorry I realized python26 is not the only legacy Python we need. Turns out we support `py{26,27,33,34,35,36,37}`

https://github.com/PythonCharmers/python-future/blob/28b336151e991ddb8d8a4fb48c48f0e2b9784f55/tox.ini#L3

So could you also help us add unofficial/no-support-whatsoever Python 3.3 and Python 3.4 support?

**Comment by adamchainz** [comment]
@sfdye alternatievly you could use deadsnakes with its github action, since the builds are already there: https://github.com/deadsnakes/action

**Comment by MaksimZhukov** [comment]
Hello @sfdye !

We've published Python `3.3.7` and `3.4.10`. These versions are available for `ubuntu-16.04` and `ubuntu-18.04`, but pay attention we faced with the same issue during running our tests as for the Python `2.6.9`

**Comment by sfdye** [comment]
@MaksimZhukov Thank you so much for the quick action. I know you folks said you won't support these legacy versions but while I am able to download `py26/py33/py34`, `pip` seems to be installed incorrectly:

https://github.com/PythonCharmers/python-future/runs/882083610?check_suite_focus=true
```
Run pip --version
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

I also have to manually install `wheel` for `py26/py33/py34`.

Is this behavior expected?

**Comment by MaksimZhukov** [comment]
We are looking at it

**Comment by sfdye** [comment]
Okay I figured out the cause.

https://pip.pypa.io/en/stable/installing/

> pip is already installed if you are using Python 2 >=2.7.9 or Python 3 >=3.4 downloaded from python.org or if you are working in a Virtual Environment created by virtualenv or pyvenv. Just make sure to upgrade pip.

So I have to manually install `pip` for python 2.6, python 3.3 and python 3.4
```yaml
- name: Install pip
  if: matrix.python-version == 2.6 || matrix.python-version == 3.3 || matrix.python-version == 3.4
  run: |
    python --version
    python -c "import ssl"
    curl https://bootstrap.pypa.io/${{ matrix.python-version }}/get-pip.py | python - 'pip==9.0.3'trap.pypa.io/${{ matrix.python-version }}/get-pip.py | python - 'pip==9.0.3'
```

After this I got:
https://github.com/PythonCharmers/python-future/runs/882213742?check_suite_focus=true
```
Run python --version
Python 3.3.7
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.3.7/x64/lib/python3.3/ssl.py", line 60, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named '_ssl'
##[error]Process completed with exit code 1.
```
It looks the the python you provided is not compiled with ssl module? 🤔

**Comment by maxim-lobanov** [comment]
Yep, it looks like ssl module was not compiled properly. We compile Python on Hosted machine where openssl 1.1.0 is installed but those legacy Python versions doesn't support it. They require openssl 1.0.0. We will try to downgrade openssl before build . But we will have to disable shared libs in this case.

**Comment by sfdye** [comment]
> But we will have to disable shared libs in this case.

Which shared libs? Will there be any impact for this?

**Comment by maxim-lobanov** [comment]
I mean `--enable-shared` flag on Python build: `The -enable-shared option ensures to build both static and dynamic Python libraries`. It builds binary that uses the dynamic loader to link with the libraries it needs

**Comment by sfdye** [comment]
Ok cool, I will wait for the recompiled version with correct ssl. Thank you for the amazing support!

**Comment by maxim-lobanov** [comment]
@sfdye , We have successfully rebuilt both 3.3.7 and 3.4.10 for Ubuntu 18.04. Both were compiled with ssl module and included pip (pip 10.0.1 for Python 3.3, pip 19.1.1 for Python 3.4). 
But unfortunately, we failed to rebuilt Python 2.6. Got a bunch of builds errors that can't be fixed quickly. Will remove 2.6.* from `versions-manifest.json` for now because currently uploaded version doesn't work properly

JFYI: `Install dependencies` step still fails for 3.3, 3.4 because you have a bunch of hardcoded versions like `tox 3.17.1` that is not available for old Pythons. Also looks like `tox-gh-actions` doesn't support old Python versions.

**Comment by MaksimZhukov** [comment]
Hello @sfdye !
Have you had a chance to test Python 3.3.7 and 3.4.10? Do these Python versions work as expected?
Please let us know if you have any questions or if you need any help.

**Comment by sfdye** [comment]
I tried but no luck yet. As Maxim has mentioned, there is a lot missing support due to legacy python versions. I am starting to think the effort was worth to migrate 🤔 since Travis was building just fine.

**Comment by konradpabjan** [comment]
Hey @sfdye 

Since it's not working we'll go ahead and remove the extra distributions of Python that we added.

I thought this would be a quick compile + publish but there appears to be a host of other problems 😟 Given that these distributions are so old and we haven't seen any other customers asking for this, we won't be officially supporting them.
