### ISSUE TITLE
Python 3.4 not installing with error: "Version 3.4 was not found in the local cache"

### ISSUE THREAD

**Issue by adamchainz** [actions/setup-python#122]
**Describe the bug**

I switched a project building on many Python versions, including 3.4, over to GitHub Actions this week, with many successful builds. Today it has started failing on the Python 3.4 install step with:

```
Version 3.4 was not found in the local cache
```

**Which version of the action are you using?**

v2.1.1

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**

3.4

**To Reproduce**

Try use Python 3.4.

**Run/Repo Url**

https://github.com/scoutapp/scout_apm_python/pull/547

**Screenshots**

n/a

**Additional context**

n/a

**Comment by konradpabjan** [comment]
Hey @adamchainz 

Python 3.4 is very old and we weren't initially planning on supporting it. There was a request for `2.6`, `3.3` and `3.4` as part of this issue: https://github.com/actions/setup-python/issues/102

We decided to quickly try out compiling and releasing the appropriate versions just to try out if it would quickly work. If there was a problem (which there was) our intention was to revert the changes since we didn't have any plans to invest resources into fixing any compile issues. It appears you used Python 3.4 during the brief period when it was made available.

Since it appears you had `3.4` working, we can re-publish just that specific distribution cc @maxim-lobanov @MaksimZhukov I also quickly checked and it looks like a year ago Python 3.4 was pre-installed on our hosted images so we can safety add it back: https://github.com/microsoft/azure-pipelines-image-generation/issues/1319 We should have kept at least that version 😕

**Comment by maxim-lobanov** [comment]
@konradpabjan , we didn't remove `3.3` and `3.4` from `actions/python-versions` (we just removed 2.6). Those versions are still there: https://github.com/actions/python-versions/blob/main/versions-manifest.json#L829

@adamchainz's build failed with pretty strange issue and it is not usual message that version is not found:
![image](https://user-images.githubusercontent.com/16715858/88707689-4c247000-d11b-11ea-89d7-860c87db9feb.png)
Looks like something went wrong during downloading manifest?

**Comment by maxim-lobanov** [comment]
@adamchainz , I have fixed the issue, could you please validate from your side?

@konradpabjan , actually, issue come from incorrect manifest structure for versions where only one file is available. I have fixed directly in main branch for now: https://github.com/actions/python-versions/commit/d20146a86c1ada6c45965bfff54fcf4b7f02ab8d
And will prepare fix for versions-manifest-generator tomorrow

**Comment by adamchainz** [comment]
Seems fixed to me! https://github.com/scoutapp/scout_apm_python/pull/551 built fine. Thank you 👍
