### ISSUE TITLE
Python 3.9.0rc2 prints warning

### ISSUE THREAD

**Issue by gaborbernat** [actions/setup-python#146]
When provisioning 3.9.0-rc.2 the following warning is raised (and printed as an annotation):

```
2020-10-02T00:25:10.7342252Z ##[error]WARNING: The scripts pip.exe, pip3.9.exe and pip3.exe are installed in 'C:\hostedtoolcache\windows\Python\3.9.0-rc.2\x64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

Example action https://github.com/pypa/virtualenv/actions/runs/283359754

Thanks,

**Comment by cclauss** [comment]
Can this be closed now that 3.9.0 is shipping?

**Comment by AraHaan** [comment]
it still happens see #156.

**Comment by dmitry-shibanov** [comment]
Hello everyone, I think the issue is caused by setup.ps1 script in the time of upgrading pip. As temporary solution you can use this code snippet to suppress this error:
```
New-Item -ItemType file -Path C:\ProgramData\pip\pip.ini -Force
Write-Output "[install]`nno-warn-script-location = no" | Out-File -FilePath C:\ProgramData\pip\pip.ini -Force
```
We will try to fix this issue from our side by rebuilding windows python version with flag `no-warn-script-location`. I'll ping the issue when it should be resolved.

**Comment by dmitry-shibanov** [comment]
Hello everyone. The root cause of the issue was that in setup.ps1 during installation pip was installing and updating but for this moment it was not set in the path. The `--no-warn-script-location = no` hides this warning. We rebuilt python 3.10th versions and warning should not appear now. For previous versions you can use upper workaround.
