### ISSUE TITLE
Add 32 Bit (x86) for older python versions e.g. 3.4

### ISSUE THREAD

**Issue by blackjack4494** [actions/setup-python#153]
https://github.com/actions/setup-python/issues/122

There is 3.4.10 as 64 Bit version available but I need the 32 Bit version. Unfortunately 3.5 or so is offering 32 Bit but that is not working out for my repo. Then there is some old 2.x 32 Bit which won't do as I need python3.  
Any chance this could be added?

**Comment by konradpabjan** [comment]
We've added support for very old Python 3.x versions but only for Windows: https://github.com/actions/setup-python/issues/157

You can see all available versions here: https://github.com/actions/python-versions/blob/main/versions-manifest.json

We will not be adding support for old 3.x distributions for Mac and Ubuntu since that requires us to manually compile from source and we've run into a host of issues building these old distributions. For Windows we just directly download and install the distributions from https://python.org
