### ISSUE TITLE
How to specify 'latest PyPy 3'?

### ISSUE THREAD

**Issue by altendky** [actions/setup-python#174]
**Describe the bug**
Previously I passed versions like `pypy3` but my attempts to use the new PyPy version formatting result in me being told to specify `x.y`.  How should I request 'latest PyPy 3' or 'latest PyPy 2'?  I understand the notes in the readme that the really latest one may take a week or two to propogate.  Unless I need it for a bug I think that's fine as opposed to having to manually update each of my projects for each release of PyPy.

I tried both `pypy-3` and `pypy-3.X`.

```
Error: Invalid format of Python version for PyPy. Python version should be specified in format 'x.y'. See README for examples and documentation.
```

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [x] Windows
- [x] Mac

If applicable, please specify if you're using a container

**Python Versions**
Please list all of the effected versions of Python (`3.8.2`, etc.)

- PyPy

**Run/Repo Url**
https://github.com/twisted/python-info-action/pull/4/checks?check_run_id=1577441885

**Comment by maxim-lobanov** [comment]
Hello @altendky ,
When you select PyPy, you can choose two versions: version of Python and version of PyPy itself.
Currently, latest version of PyPy 7.3.3 and they provide 3 versions of Python: 2.7, 3.6, 3.7.

Version of PyPy can be specified as SemVer notation like `7.x`, `7.3.x` and etc or can be skipped at all (in this case, latest version will be used).
Version of Python should be always provided as a full version `2.7`, `3.6`, `3.7`. It was done intentionally to avoid ambiguity when specifying both Python and PyPy with `.x`. Also, previously we could not update `pypy3` keyword to 3.7 instead of 3.6 because it breaks a lot of customers pipelines. So we have decided to force customers to specify full Python part always.

I suggest specifying exact python version like `pypy-3.6` or `pypy-3.7` to avoid build breaks when 3.8 or 3.9 is released.

**Comment by altendky** [comment]
It seems it would be useful to be able to get 'latest 3' as you can in other cases, but thanks for the detailed explanation.
