### ISSUE TITLE
Started failing today: Version 3.4 was not found in the local cache

### ISSUE THREAD

**Issue by rexcsn** [actions/setup-python#185]
**Describe the bug**
Cannot install python 3.4 with setup-python today. Workflow was working until yesterday.
Error messages:
```
Version 3.4 was not found in the local cache
Error: Version 3.4 with arch x64 not found
```
Error run: https://github.com/aws/aws-parallelcluster/runs/1771959071?check_suite_focus=true 
Successful run from yesterday: https://github.com/aws/aws-parallelcluster/runs/1763215835?check_suite_focus=true

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

No

**Python Versions**
3.4.x

**To Reproduce**
See error from step `Python 3.4 test`

**Run/Repo Url**
Error run: https://github.com/aws/aws-parallelcluster/runs/1771959071?check_suite_focus=true 
Successful run from yesterday: https://github.com/aws/aws-parallelcluster/runs/1763215835?check_suite_focus=true

**Comment by dmitry-shibanov** [comment]
Hello @rexcsn . I think the root cause of the issue is ubuntu-latest label currently uses the Ubuntu-20.04 instead of 18.04. There is an announcement in the actions/virtual-environments repository: [Ubuntu-latest workflows will use Ubuntu-20.04](https://github.com/actions/virtual-environments/issues/1816). Please find more details in this announcement. Unfortunately, we don't provide python 3.4.x binaries for Ubuntu-20.04. All available python versions you can find in the [versions-manifest.json](https://github.com/actions/python-versions/blob/main/versions-manifest.json).
As a solution, you can switch back to Ubuntu-18.04 by specifying the `ubuntu-18.04` label in your workflow.

**Comment by rexcsn** [comment]
Hi @dmitry-shibanov,

Thank you for the prompt reply! We can go ahead and close this issue.
