### ISSUE TITLE
v1 tag missing for a while?

### ISSUE THREAD

**Issue by tannewt** [actions/setup-python#21]
Was the v1 tag deleted for a bit? We had trouble downloading the action tarball yesterday. What version should we tie ourselves to?

![Screen Shot 2019-09-12 at 12 35 20 PM](https://user-images.githubusercontent.com/52649/64815373-4bfaa080-d55a-11e9-852d-fb42d8f7b5ff.png)

**Comment by tannewt** [comment]
Hi @damccorm we're still seeing this: https://github.com/adafruit/circuitpython/runs/221905026

Is it possible there is a rate limit we're hitting? We're doing ~70 jobs concurrently for every build.

**Comment by konradpabjan** [comment]
Hi @tannewt have you recently had this issue? Looking at some of your recent runs they all appear to be running and not hitting the issue described. I'm suspecting there may have been a period of time where some unrelated issue on Github was causing this to happen.

If you do get rate limited, you should see an error like this with our new annotations feature: 
![image](https://user-images.githubusercontent.com/16109154/68238598-7c4d4100-ffd7-11e9-9acf-6b15db25ef65.png). The expected behavior is that a job starts only if no caps or limits have been hit, once it's running an unauthorized download of an action should not happen and it's indicative of some other problem going on.

**Comment by tannewt** [comment]
@konradpabjan I haven't seen it recently and assume it's been fixed. Thanks!
