### ISSUE TITLE
RFE: add Pyston

### ISSUE THREAD

**Issue by scop** [actions/setup-python#234]
**Describe the bug**

Not really a bug, but a feature request: would be nice to have Pyston available for install in Actions (multiple versions, like other variants).

Their words:
> Pyston is a fork of CPython 3.8.8 with additional optimizations for performance. It is targeted at large real-world applications such as web serving, delivering up to a 30% speedup with no development work required.

https://www.pyston.org
https://github.com/pyston/pyston

There are portable ready to run tarballs and .debs available at https://github.com/pyston/pyston/releases

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**

https://github.com/pyston/pyston/releases -- 2.2 and 2.3 available at the moment.

**To Reproduce**

Specify `pyston3` or `pyston-2.3` as `python-version'.

**Run/Repo Url**

https://www.pyston.org
https://github.com/pyston/pyston

**Screenshots**

-

**Additional context**

-

**Comment by dmitry-shibanov** [comment]
Hello @scop. We're going to close the feature request because pyston uses deb extension for installing python that is why we can't specify the path where the binaries will be unpacked. Besides, we won't be able to override python to pyston because it will be the conflict with default python on the runners. Moreover, we can get some issues with installing it on Ubuntu because of permissions or because apt-get (other tools) won't be available. You can use pyston docker image or download pyston lite.
