### ISSUE TITLE
Error: Version 2.7 with arch x64 not found (macOS)

### ISSUE THREAD

**Issue by exarkun** [actions/setup-python#313]
**Description:**

Setting up Python 2.7 on any macOS environment fails with the error in the issue title.

**Action version:**

v1

**Platform:**
- [ ] Ubuntu
- [X] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

Python 2.7

**Repro steps:**  

https://github.com/tahoe-lafs/zfec/blob/4eb5c7c99a6a7c5568e3567d3e135ce840e81acb/.github/workflows/test.yml#L39-L42

**Expected behavior:**

Python 2.7 to be installed.

**Actual behavior:**

An  error is reported and Python 2.7 is not available.

**Comment by nikita-bykov** [comment]
Hello @exarkun, thanks for your report!

`setup-python/v1` can select the Python version only if it is installed on the machine ([the list of available Python versions for macos-latest](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#python)). Since version 2.7 is not preinstalled on the macOS 11 (macos-latest) image, your builds fail.
We suggest you to use `setup-python/v2` which can download and install versions from [python-versions](https://github.com/actions/python-versions), it will install Python 2.7 on macos-latest successfully.

I'm going to close the issue, but feel free to contact us if have any questions.

**Comment by exarkun** [comment]
Thanks.  v2 was indeed able to get Python 2.7 on macos.
