### ISSUE TITLE
Add 3.x-1 version support

### ISSUE THREAD

**Issue by matham** [actions/setup-python#337]
**Description:**
Please add support for selecting a version of python that is one minor version older than what `3.x` selects. E.g. if `3.x` selects `3.10`, then it should select `3.9`.

**Justification:**
The reason for this is that every time a new python is released, many CI that use `3.x` is likely to fail for some time. That's because it takes a while for projects to release wheels for the latest python.

For some actions, the failure is a good signal, but for other, where you don't need the latest, you just want a functioning python, your option is to either hard code a python version and them bump it every few years, or use `3.x` and risk failures for a bit after a new python is released.

With this option you'd use a fairly recent python, but not so recent that it will risk failing once a year for a bit.

**Comment by nikita-bykov** [comment]
Hello @matham, thanks for your report!
We'll take a look at it.

**Comment by dmitry-shibanov** [comment]
Hello @matham. Thank you for your report. We won't be implementing such kind of logic because it does not comply with the latest semver notation for 3.x and will be an unexpected behaviour if users need the latest version.

Please use specific python version if you do not need the latest one. For now I'm going to close the feature request.
