### ISSUE TITLE
Ability to install "latest pypy3"

### ISSUE THREAD

**Issue by scop** [actions/setup-python#360]
**Description:**

Ability to install the latest PyPy 3 available would be great, for example by specifying `pypy-3.x`.

Originally discussed in https://github.com/actions/setup-python/issues/352

**Justification:**

Same justification as the existing ability to install the latest CPython 3 by specifying `3.x`.

**Are you willing to submit a PR?**

In general yes, in practice it's unlikely I'd have time for this in the near future.

**Comment by dmitry-shibanov** [comment]
Hello @scop. Thank you for your report. We'll investigate your feature request.

**Comment by marko-zivic-93** [comment]
Hello @scop. 
I think it can be misleading to install pypy3 as the latest one because we can have a case with python or pypy version that is greater than the selected one. That is why we can't determine which version should be considered as the latest one.
Due to this fact, we will not pursue adding this feature to this action.

Thank you for reporting this to us! 
If you have any additional questions or concerns, please feel free to contact us.

**Comment by scop** [comment]
I disagree with the reasoning. To me, `pypy-3.x` is easily understandable, following the already documented convention at https://github.com/actions/setup-python#usage:

> `'pypy-3.8' # the latest available version of PyPy that supports Python 3.8`

Along those lines, this would mean just

> `'pypy-3.x' # the latest available version of PyPy for the latest Python 3.x version that PyPy supports`

**Comment by dmitry-shibanov** [comment]
Hello @scop. Thank you for your response. I think we can have a situation where the latest python might not have the latest PyPy version. It can lead to an unexpected result.

**Comment by scop** [comment]
I see nothing unexpected there. It's very much expected and actually the normal state of affairs that the latest PyPy lags behind the latest CPython minor version.
