### ISSUE TITLE
Allow poetry cache to work without lock file

### ISSUE THREAD

**Issue by dhvcc** [actions/setup-python#372]
**Description:**
I want to propose adding a feature to allow `cache: poetry` to work without `poetry.lock` file. Currently it'll fail (I'm not sure if this is a bug).

**Justification:**
Some projects may not want to push their lock files to the repo and it will still be a valid poetry project, but current implementations has `poetry.lock` kind of hardcoded. Obviously poetry will still have to resolve all of the dependencies, which is slow, but I think it's not right to fail on a fully valid poetry project.

**Are you willing to submit a PR?**
Yes.

**Comment by dmitry-shibanov** [comment]
Hello @dhvcc. Thank you for your proposal. Actually we rely on the poetry.lock file, because the action needs to generate hash from the dependencies' file. If one of the dependencies change, the action will resave cache. You can try to use the `cache-dependency-path` input. It will override a dependencies' file, so you can link to another file.

**Comment by dhvcc** [comment]
> Hello @dhvcc. Thank you for your proposal. Actually we rely on the poetry.lock file, because the action needs to generate hash from the dependencies' file. If one of the dependencies change, the action will resave cache. You can try to use the `cache-dependency-path` input. It will override a dependencies' file, so you can link to another file.

Yeah, nice catch. Thanks! I wasn't reading carefully it seems and missed the part of 

> Use cache-dependency-path for ... or **different files for the hash want to be used.**
