### ISSUE TITLE
Python 3.9.7 not found

### ISSUE THREAD

**Issue by jjnanthakumar** [actions/setup-python#378]
**Description:**
Till last week I was able to deploy the Django web application using GitHub Actions, when I tried today it was throwing some dependency error in Azure App service Deploy Task.

Finally, I found the root cause, successfullly deployments are using python 3.9.7 and now it seems updated (3.9.12)

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

3.9.7, 3.9.9

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by dmitry-shibanov** [comment]
Hello @jjnanthakumar. Thank you for your report. I think it's not related to setup-python, because the step with seting up python version was finished successfully. If you think it's related to how the python was built could you please provide repro steps or public repository to reproduce the issue ?

**Comment by jjnanthakumar** [comment]
Yes, sorry the actual problem is in Azure side. 

I am closing this now. 

Thanks.
