### ISSUE TITLE
Request: no-hash option

### ISSUE THREAD

**Issue by PerchunPak** [actions/setup-python#380]
**Description:**
Add `no-hash` option. It will disable adding hash in cache key. So instead of `setup-python-{os}-python-{python_version}-{package_manager}-{hash("dependency file")}` we will have `setup-python-{os}-python-{version}-{package_manager}` in key.

P.S. How about pass to `{python_version}` (from key) only major and minor versions (X.X.~~x~~), example 3.10 instead of 3.10.4?

**Justification:**
Whould be usefull to **update** dependecies instead of re-install all them again.

**Are you willing to submit a PR?**
Sorry, but I don't know codebase at all.

**Comment by vsafonkin** [comment]
Hi @PerchunPak, we will take a look at it, thank you for your report!

**Comment by dmitry-shibanov** [comment]
Hello @PerchunPak. Thank you for your report. We would not like to implement such kind of logic, because the initial caching logic for setup-python should cover the most often use cases. If you want to use some more complex caching logic we would recommend you to use [actions/cache](https://github.com/actions/cache). It's relevant to setup-node [ADR](https://github.com/actions/setup-node/blob/main/docs/adrs/0000-caching-dependencies.md#goals--anti-goals).

For now I'm closing the issue.
