### ISSUE TITLE
Failing on ubuntu 22.04

### ISSUE THREAD

**Issue by fennerm** [actions/setup-python#391]
**Description:**
Our github actions started failing at the setup-python step this morning with message: `Error: Version 3.7 with arch x64 not found`. I believe the issue is related to the ubuntu 22.04 release yesterday. Downgrading our ubuntu version to 20.04 resolved.

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
'3.7' (also tested with '3.7.12')

**Repro steps:**  
Run setup-python in a github action with `runs-on: ubuntu-latest`  

**Expected behavior:**
Python 3.7.12 is installed.

**Actual behavior:**
Error:
```
/usr/bin/docker exec  49e273287cc45bae2be91888edcaa22ac8409b4c98dc7fd02d8fce1f58fc512e sh -c "cat /etc/*release | grep ^ID"
Version 3.7 was not found in the local cache
Error: Version 3.7 with arch x64 not found
```

**Comment by marko-zivic-93** [comment]
Hello @fennerm,
Can you please confirm both 22.04 and 20.04 builds have environment variable AGENT_TOOLSDIRECTORY set according to https://github.com/actions/setup-python/blob/main/README.md#linux ?

Anyway  @dsame should take a look  to `tc.find` (find specific version in tool cach) called from src//find-python.ts:41 and double check it has the same behavior with 22.04 and 20.04

**Comment by vivekjainx86** [comment]
I faced same issue while using `ubuntu:latest` container for `setup-python` action. Using `ubuntu:20.04` has solved the issue.

If you refer [version-manifest.json ](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) file, you will see there is no matching platform version for `ubuntu:22.04` and that's why we see error: `Error: Version 3.7 with arch x64 not found`

@dsame Your repro attempt worked because you used Github action's runner `ubuntu:latest` which is still Ubuntu 20.04 (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

**Comment by BlueskyFR** [comment]
I am having the same issue on a Docker Github Actions runner

**Comment by mayeut** [comment]
Python 3.7 -> 3.10 are now available for ubuntu 22.04: https://github.com/actions/python-versions/pull/161

**Comment by dsame** [comment]
@fennerm much thanks to @vivekjainx86  i understood the issue and it seems to be resolved with https://github.com/actions/python-versions/pull/161 but i still have a concern about "self-hosted" and "docker" cli you've mentioned in the description. 

Please let us know do you still have an issue with the build or, it can be closed as resolved?

**Comment by vivekjainx86** [comment]
@dsame I don't see any problem with my build now, the issue can be closed as resolved.

**Comment by marko-zivic-93** [comment]
Hello guys,
If this is the case I will close this issue. You feel free to leave a comment here or to create a new issue if any new issues occur :)
