### ISSUE TITLE
Unclear note

### ISSUE THREAD

**Issue by Masynchin** [actions/setup-python#392]
This is question about README, not a bug report.

**Description:**

I see this note in [caching section](https://github.com/actions/setup-python#caching-packages-dependencies):

> Please Note: Restored cache will not be used if the requirements.txt file is not updated **for a long time** and a **newer version of the dependency is available** that can lead to an increase in total build time.

How much is **long time**? Why **newer versions of dependencies** affects cache? Does it mean that using the same requirements.txt file can't guarantee always cache hit?

**Expected behavior:**
Always cache hit on same requirements.txt.

**Comment by marko-zivic-93** [comment]
Hello @Masynchin 
It is necessary to clarify the README with the exact time periods and the reasons cause the cache may not be used.

**Comment by dmitry-shibanov** [comment]
Hello @Masynchin. Thank you for your report. For pip the action caches global cache directory, which it gets through the `pip cache dir` command. The [primary key](https://github.com/actions/setup-python/blob/main/src/cache-distributions/pip-cache.ts#L60) depends on python-version and a hash from dependencies' file. The hash is generated from the requirements.txt file by default. In the requirements.txt file users can specify ranges to use versions higher than some versions, that is why different version of dependencies can be installed for the same primary key because the hash based on requirements.txt won't be renewed. The step with installation dependencies will be longer, because new versions of dependencies will be installed with old cache.

**Comment by Masynchin** [comment]
> In the requirements.txt file users can specify ranges to use versions higher than some versions, that is why different version of dependencies can be installed for the same primary key because the hash based on requirements.txt won't be renewed.

Does it mean that if I use strict versions (`somelib==0.1.0`) it wont result dependency installation?

**Comment by Masynchin** [comment]
@dmitry-shibanov it will be always *blazing fast* installation, or it will re-install dependencies sometimes?

**Comment by dmitry-shibanov** [comment]
For pip the action caches global cache directory which contains http responses and locally built wheels. The action does not cache site packages that is why you need to call install command. 
For `pipenv` the action caches `virtualenv` directory that is why If cache-hit is true an installation of dependencies can be skipped.

**Comment by dmitry-shibanov** [comment]
Hello @Masynchin. For now I'm going to close the issue if you have any concerns feel free to ping us.
