### ISSUE TITLE
windows: Pre-installed mingw python2.7.exe causes issues

### ISSUE THREAD

**Issue by sbc100** [actions/setup-python#40]
When trying use this action I had some trouble with the preexisting python2.7.exe that exists in the PATH.    Specifically I ran in two separate issues:

1. cmake can end up choosing mingw python2.7.exe over the setup-python configured python.exe.  For example if you have `find_package(PythonInterp 2.7 REQUIRED)` in your cmake file then cmake will always prefer the explicit python2.7.exe in the PATH.  

2. The mingw version of python fails when argv[1] contained withing directory separators.   In this case it fails to set the initial python path correctly.   This causes issues for subprocesses too, for example if you construct the name of a python script with  with `os.path.join` and then try to run it with `sys.executable` is can file.  I constructed a simple repo to demonstrate this problem:

https://github.com/sbc100/python-mingw-fail/runs/316815593

As you can see the `python2.7 with windows path` step fails because `sys.path[0]` is not set correctly.

Possible solutions:

1. Remove mingw's `python2.7.exe` from `$PATH`.  This would be ideal for my use case.
2. Add `python2.7.exe` to `C:\hostedtoolcache\windows\Python\2.7.16\x64`
3. Fix this seeming bug in mingw python. 

(3) is actually not that great of solution because really the point of using `setup-python` is that it should be in control of the version of python that gets uses, and using the mingw python seems wrong.

**Comment by konradpabjan** [comment]
We add `MinGW` to PATH by design. We use `choco install -y mingw` to install it. This was added mostly to support `GCC` and `make`. It's rather an unintended consequence that Python 2.7 also gets added to PATH.

Whatever is in `hostedtoolcache` is Python that we manage ourselves. For Linux and Mac this is Python that we compile while for Windows we download it directly from https://www.python.org/downloads/windows/ so it doesn't make sense to throw in another distribution here.

It is possible to manually remove a variable from PATH without too much effort using Powershell on Windows so that's the best I can recommend if this is a blocker.

**Comment by sbc100** [comment]
Yes, its really that "unintended consequence" that is the problem.  

I quite like to keep mingw in the path, but ideally without a broken python2.7 in there.   I is there a way you can install mingw without python?

(Its  unfortunate that the windows python distribution doesn't include "python2.7.exe" as well as "python.exe" since then putting your python path first would cause it to override the mingw one, which would be desirable)
