### ISSUE TITLE
Support Amazon Linux

### ISSUE THREAD

**Issue by collin-miller** [actions/setup-python#460]
**Description:**
The setup python action doesn't work on anything but ubuntu. I am sure many of your clients who self-host runners are using Amazon linux distributions. 

**Justification:**
You don't support anything other than ubuntu for self hosted runners.

**Are you willing to submit a PR?**
yes

**Comment by IvanZosimov** [comment]
Hi, @collin-miller 👋 ! Thanks for the feature request, we will take a look at this idea and get back to you with some updates :)

**Comment by collin-miller** [comment]
@IvanZosimov have you considered the impact this has on your self-hosted customers?

**Comment by PavanMudigondaTR** [comment]
Please support Debian Amazon Linux 2

<img width="626" alt="image" src="https://user-images.githubusercontent.com/86745613/203861065-cf849b89-b4e5-420e-9973-7386dbec14cb.png">
<img width="466" alt="image" src="https://user-images.githubusercontent.com/86745613/203861094-ff149a0a-4c14-4392-a742-8e62fb685855.png">

**Comment by austinmw** [comment]
Would also love to see Amazon Linux support

**Comment by kishaningithub** [comment]
Since this setup-python github action is not supporting amazon linux and has no foreseeable plans of doing so, i have created an open source action to support the same

https://github.com/kishaningithub/setup-python-amazon-linux

The goal is to be a drop-in replacement to the maximum extent possible. Feedback and contributions are most welcome! :-)
