### ISSUE TITLE
Unable to locate lsb_release

### ISSUE THREAD

**Issue by bend-n** [actions/setup-python#556]
**Description:**
The step fails with this error:
```
Error: Unable to locate executable file: lsb_release. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Hosted

**Tools version:**

3.9.15

**Repro steps:**  
Failing: [hammer_space/run#3610973067/job#6085551293](https://github.com/bend-n/hammer_space/actions/runs/3610973067/jobs/6085551293#step:3:542)

Workflow: [setup.yml](https://github.com/bend-n/godot-actions/blob/main/.github/actions/setup-godot/action.yml)

**Expected behavior:**
No error

**Actual behavior:**
Error

**Comment by dmitry-shibanov** [comment]
Hello @bend-n. Thank you for your report. It looks like your custom ubuntu images in docker does not have lsb_release tool. The tool is used to get the version of Ubuntu. Could you please try to use this command: `apt-get update && apt-get install -y lsb-release && apt-get clean all` to install the tool or you can try disabling the cache because the [tool](https://github.com/actions/setup-python/blob/main/src/utils.ts#L125) is called when  the cache is enabled.

**Comment by bend-n** [comment]
> Hello @bend-n. Thank you for your report. It looks like your custom ubuntu images in docker does not have lsb_release tool. The tool is used to get the version of Ubuntu. Could you please try to use this command: `apt-get update && apt-get install -y lsb-release && apt-get clean all` to install the tool or you can try disabling the cache because the [tool](https://github.com/actions/setup-python/blob/main/src/utils.ts?rgh-link-date=2022-12-04T23%3A31%3A35Z#L125) is called when the cache is enabled.

I have tried this actually.
https://github.com/bend-n/godot-actions/commit/366c5c69024356b31ced880f9bf63ff47691d1a1

**Comment by bend-n** [comment]
Ill try disabling the cache though.

**Comment by bend-n** [comment]
I dont know how, and i dont know how, this was happening, and I do not care, so long as it doesnt happen again.

**Comment by alramalho** [comment]
Still happening
