### ISSUE TITLE
More explicit error messages for network issues

### ISSUE THREAD

**Issue by ikamensh** [actions/setup-python#614]
I'm working on a windows machine behind a proxy, and I'm trying to setup GH Actions Runner on it. When trying to run `setup-python` I get an error below:
```
Run actions/setup-python@v4
  with:
    python-version: 3.9
    check-latest: false
    update-environment: true
  
Installed versions
  Version 3.9 was not found in the local cache
  Error: tunneling socket could not be established, statusCode=403
```

**Description:**
Instead of `  Error: tunneling socket could not be established, statusCode=403` I'd like to know what host was accessed and maybe some explanation of what went wrong. Probably 403 means I failed to authenticate somewhere?

**Justification:**
The current error is cryptic and leaves me (and maybe other users) guessing at what went wrong. Does the action get python from python.org? github.com? some other website? where do I need to auth?

**Are you willing to submit a PR?**
Perhaps, but I'm not sure I can do it.

**Comment by e-korolevskii** [comment]
Hello @ikamensh!
We will investigate this feature request and get back to you as soon as we have updates.

**Comment by dmitry-shibanov** [comment]
Hello @ikamensh. Thank you for your report. It looks like you have issue with firewall or proxy. I think it fails to get access for [manifest file](https://github.com/actions/go-versions/blob/main/versions-manifest.json). I'm not sure that we can improve the error message because the action downloads manifest file through the function in the toolkit. Besides, the error message contains information about status code and information about it.

For now I'm going to close the feature request.

**Comment by ikamensh** [comment]
Well, if there was any message for what the tool is about to do before the error I'd know it too. Is there some verbose setting for debugging such issues?

**Comment by dmitry-shibanov** [comment]
Hello @ikamensh. You can try to enable [debug logging](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging).
