### ISSUE TITLE
Error: Cache folder path is retrieved for poetry but doesn't exist on disk

### ISSUE THREAD

**Issue by ylilarry** [actions/setup-python#653]
**Description:**
My CI is failing with this error in the `Post job cleanup` step, I don't know what it means:

    Post job cleanup.
    Error: Cache folder path is retrieved for poetry but doesn't exist on disk: /home/runner/.cache/pypoetry/virtualenvs, /home/runner/work/FastchargeAPI/FastchargeAPI/.venv

My workflow file is simply:

    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        cache: "poetry"

**Action version:**
'actions/setup-python@v3' (SHA:48e4ac706204bab735867521ba54b3276c883d00)

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python3.9, Python3.10

**Comment by ylilarry** [comment]
Can someone explain to me why it is trying to look for a cache folder in `.venv` and why is that `.venv` missing? This is not coming from my code. I think it's something internal to setup-python.

**Comment by dmitry-shibanov** [comment]
Hello @ylilarry, just a gentle ping.

**Comment by ylilarry** [comment]
Hi, let me check it tonight. Thanks for the reminder.

**Comment by MaksimZhukov** [comment]
Hello @ylilarry !
Have you had a chance to prepare a public repository for further investigation?

**Comment by ylilarry** [comment]
The problem is sporadic and I can't reproduce it. Will take a look if this happens again.

**Comment by sezanzeb** [comment]
I'm having a similar error message with `cache: 'pip'`: https://github.com/sezanzeb/input-remapper/actions/runs/5365366969/jobs/9734150591#step:9:2

Should I open a separate issue for that? Is something on our side broken?

**Comment by dmitry-shibanov** [comment]
Hello @sezanzeb. Could you please open a separate issue ?

**Comment by devanubis** [comment]
When I came across this problem, it turned out to be because my project was using a local `.venv` in development (to give the \`pyright\` pre-commit hook easy access to our dependencies and types)

And in our ci workflow, `poetry` was then installing to that `.venv` too, but `setup-python` was still looking for the poetry virtual environment in `/home/runner/.cache/pypoetry/virtualenvs`.

I just added a step to our ci workflow to `rm -rf .venv` since we don't need/want a local venv in ci.

Might help anyone else running into this.
