### ISSUE TITLE
pip caching does not persist across branches

### ISSUE THREAD

**Issue by charles-cooper** [actions/setup-python#667]
**Description:**
as title

**Action version:**
setup-python@v4

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted

**Tools version:**
python3.11 

**Repro steps:**  
after merging https://github.com/vyperlang/vyper/pull/3436, I would have expected the pip caches uploaded in https://github.com/vyperlang/vyper/actions/runs/5026057259/jobs/9013853288 (see screenshot):
![Screenshot from 2023-05-19 15-09-40](https://github.com/actions/setup-python/assets/3867501/aa735e8c-b766-421a-ae8d-60507f9c65ac)

to persist to other branches. however, they apparently did not: https://github.com/vyperlang/vyper/actions/runs/5027283557/jobs/9016578225 (see screenshot)
![Screenshot from 2023-05-19 15-10-34](https://github.com/actions/setup-python/assets/3867501/c4d473ba-0741-492b-959d-1d9400198ad5)

**Comment by dusan-trickovic** [comment]
Hello, @charles-cooper ! Thank you for creating the issue, we will take a look at it :)

**Comment by dmitry-shibanov** [comment]
Hello @charles-cooper. Sorry for the late response. I think it is an expected behaviour because the cache is saved only for the default branch (main). Could you please take a look at this links for more information:
 - https://github.com/actions/cache#cache-scopes
 - https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

**Comment by charles-cooper** [comment]
Ok I see, thank you!
