### ISSUE TITLE
Error: Cache folder path is retrieved for pip but doesn't exist on disk

### ISSUE THREAD

**Issue by sezanzeb** [actions/setup-python#691]
**Description:**

`Error: Cache folder path is retrieved for pip but doesn't exist on disk: /home/runner/.cache/pip`:

https://github.com/sezanzeb/input-remapper/actions/runs/5365366969/jobs/9734150591#step:9:2

**Action version:**

3 and 4 (a bit more information is below)

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Affects python 3.7, but not 3.11 for version 4

Affecty python 3.7 and 3.11 for version 3 ([setup-python v3](https://github.com/sezanzeb/input-remapper/pull/730/commits/5d40687ed19a2c045de9d1d7b15d728c977afe0d))

**Repro steps:**  

Links are above

**Expected behavior:**

To not fail

**Actual behavior:**

It fails

**Comment by dmitry-shibanov** [comment]
Hello @sezanzeb. Thank you for your report. We'll take a look at it.

**Comment by dmitry-shibanov** [comment]
Hello @sezanzeb. Sorry for the late response. I think it is an expected behaviour because you use pip with sudo. You get different cache directories because setup-python calls pip as `pip cache dir`. Possibly it works for python 3.10 because it uses already saved cache that is why when you use different version of setup-python it fails because the action tries to save cache but it does not exist in `pip cache dir` directory.

**Comment by sezanzeb** [comment]
Oh, sorry, I forgot about it. Thanks for looking into this!
