### ISSUE TITLE
Python 3.12 fails to setup on `container` builds

### ISSUE THREAD

**Issue by LecrisUT** [actions/setup-python#718]
**Description:**
Interestingly the python setup works fine for the container (Fedora 38) with other versions of python, but the `Python 3.12` with `allow-prerelease` fails for this. Is it that this version is not built for most OS? Is there a workaround for this?

[Example run](https://github.com/spglib/spglib/actions/runs/5857856317/job/15880659367?pr=287):
```
Error: The version '3.12' with architecture 'x64' was not found for this operating system.
```

**Action version:**
`actions/setup-python@v4`

**Platform:**
- [x] Ubuntu (container)
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Comment by dmitry-shibanov** [comment]
Hello @LecrisUT. Thank you for your report. We'll take a look at this issue.

**Comment by dmitry-shibanov** [comment]
Hello @LecrisUT. Sorry for the late response. I think it is an expected because your container does not have `/etc/lsb-release` or `/etc/os-release` that is why the [toolkit/tool-cache](https://github.com/actions/toolkit/blob/7b617c260dff86f8d044d5ab0425444b29fa0d18/packages/tool-cache/src/manifest.ts#L128) library can't identify os and its version. You can try to install `lsb-release` or create `/etc/lsb-release` file like this 
```
echo -en 'DISTRIB_ID=Ubuntu\nDISTRIB_RELEASE=22.04\nDISTRIB_CODENAME=jammy\nDISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"' >> /etc/lsb-release
```

After that the action will be able to install python 3.12. For now I'm going to close the issue.

**Comment by dmitry-shibanov** [comment]
Hello @LecrisUT. It does not contain `DISTRIB_RELEASE` that is why I think you need to initialise `/etc/lsb-release`. After I initialised it the python 3.12 was installed.

**Comment by LecrisUT** [comment]
@dmitry-shibanov Can you point me to the internal code? I looked to the link you last sent and it contains a check for [`VERSION_ID`](https://github.com/actions/toolkit/blob/7b617c260dff86f8d044d5ab0425444b29fa0d18/packages/tool-cache/src/manifest.ts#L140) which is the ID number for Fedora releases. Note that this is a Fedora container and I do not want to add an ubuntu-like file like that that could affect other CIs.

Do you have any debug runner with more verbose logging that can show where `setup-python` is failing?

**Comment by dmitry-shibanov** [comment]
For now python-versions repository have versions built against Linux images from hosted runners. The hosted toolcache directory will be updated with python 3.12 after the stable version will be released.
