### ISSUE TITLE
List supported python versions in the README

### ISSUE THREAD

**Issue by adithyabsk** [actions/setup-python#72]
^ It seems that when running ci that only the latest minor python version is supported not all patch versions, it might be useful to document that. Or, if I'm wrong documenting the specific supported versions could also help!

**Comment by konradpabjan** [comment]
In the `README` you can find a link to documentation that lists the available versions: https://github.com/actions/setup-python#available-versions-of-python

The reason we don't directly include the names in the `README` is because they automatically get updated in the linked docs every-time images get built and rolled out since Python comes pre-sinstalled in the tools cache on our images. That happens here for example: https://github.com/actions/virtual-environments/blob/0ddeb1ac4b2e81f45ba752d49ec5825b77141d40/images/linux/scripts/installers/hosted-tool-cache.sh#L52

**Comment by adithyabsk** [comment]
@konradpabjan Okay, thanks for the link
