### ISSUE TITLE
Getting intermittent 401 error 

### ISSUE THREAD

**Issue by sushovan23** [actions/setup-python#733]
**Description:**
  Error: WARNING: 401 Error, Credentials not correct for https://espresso-dev-886686983283.d.codeartifact.us-east-1.amazonaws.com/pypi/espresso-dev/simple/pip/
  Error: ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
  Error: ERROR: No matching distribution found for pip
  Error: The process '/bin/bash' failed with exit code 1
**Action version:**
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

**Platform:**
  Ubuntu

**Runner type:**
Hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by marko-zivic-93** [comment]
Hello @sushovan23 🙂 
We will investigate this issue and come back to you as soon as we have some news about it 😄

**Comment by rmeppa001c** [comment]
Any update on this isue?

**Comment by aparnajyothi-y** [comment]
Hello @sushovan23, Thank you for creating this issue. It seems the issue might be related to authentication with the CodeArtifact repository. Please ensure that your credentials for the repository are correctly configured. Also, verify that the repository URL is correct and accessible from the runner.

Additionally, can you confirm if this issue is still occurring with the latest version of the action?

If you have any updates or additional logs, please share them so we can assist you further. Please feel free to reach out in case of any further clarifications needed.

**Comment by aparnajyothi-y** [comment]
Hello @sushovan23, Gentle reminder! Can you confirm if this issue is still occurring with the latest version of the action? 
If you have any updates or additional logs, please share them so we can assist you further. Feel free to reach out if you need any further clarifications.

**Comment by sushovan23** [comment]
Hello I had proceeded to using my own custom action for setup Python using docker image which had necessary packages. If you do not see it anymore it can be closed

**Comment by aparnajyothi-y** [comment]
Hello @sushovan23, Proceeding to close this issue as it no longer appears to be occurring. Please feel free to reopen it if the issue resurfaces.
