### ISSUE TITLE
Docs: `Available versions of Python and PyPy` returns 404

### ISSUE THREAD

**Issue by noqcks** [actions/setup-python#788]
In the README the link `Available versions of Python and PyPy` returns a link here which 404s

https://github.com/actions/setup-python/blob/main/advanced-usage.md#available-versions-of-python-pypy-and-graalpy

**Comment by HarithaVattikuti** [comment]
Hello, @noqcks ! Thank you for reporting this issue, we will look into it :)

**Comment by priyagupta108** [comment]
Hello @noqcks, The [PR](https://github.com/actions/setup-python/pull/793) concerning the broken link in the README has been merged and the issue is now resolved. For reference, you may visit the fixed link here [Available versions of Python, PyPy and GraalPy](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#available-versions-of-python-pypy-and-graalpy). 
Thank You !
