### ISSUE TITLE
python-3.7.17-darwin-x64 has broken readline module due missing libncurses

### ISSUE THREAD

**Issue by ludwigschwardt** [actions/setup-python#859]
**Description:**

The [latest Python 3.7 distribution](https://github.com/actions/python-versions/releases/download/3.7.17-5356448435/python-3.7.17-darwin-x64.tar.gz) on macos-13 has a broken readline module, because it is linked against a local libncurses 6 (and libreadline 8) but the runner image doesn't seem to have those files. I would have expected it to be linked against the system libncurses 5.4 and libedit instead. The other Python versions are fine. 

**Action version:**

setup-python@v5

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

3.7.17

**Repro steps:**

Download and untar the above tarball and run `otool -L` on the readline extension module.

**Expected behavior:**

From the [3.6.15-darwin-x64 tarball](https://github.com/actions/python-versions/releases/download/3.6.15-116025/python-3.6.15-darwin-x64.tar.gz):
```
$ otool -L lib/python3.6/lib-dynload/readline.cpython-36m-darwin.so 
lib/python3.6/lib-dynload/readline.cpython-36m-darwin.so:
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```
From the [3.8.18-darwin-x64 tarball](https://github.com/actions/python-versions/releases/download/3.8.18-5997368067/python-3.8.18-darwin-x64.tar.gz):
```
$ otool -L lib/python3.8/lib-dynload/readline.cpython-38-darwin.so 
lib/python3.8/lib-dynload/readline.cpython-38-darwin.so:
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```
**Actual behavior:**
```
$ otool -L lib/python3.7/lib-dynload/readline.cpython-37m-darwin.so 
lib/python3.7/lib-dynload/readline.cpython-37m-darwin.so:
	/usr/local/opt/readline/lib/libreadline.8.dylib (compatibility version 8.2.0, current version 8.2.0)
	/usr/local/opt/ncurses/lib/libncursesw.6.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```
The following then fails in the Python shell: `import readline`.

**Comment by ludwigschwardt** [comment]
Given that Python 3.7 is soon on the chopping block, it might not be worth fixing this 😅

**Comment by aparnajyothi-y** [comment]
Hello Everyone, The actions/setup-python repository does not support x64 packages for Python <3.11 version on macOS arm64 runners due to compatibility and build issues. The build process for Python versions less than 3.11 involves downloading the official Python sources from python.org and building them using the make tool on the oldest available version of macOS that was available when that Python version was released. This is done to ensure backward compatibility for those Python versions as mentioned in this python-versions [documentation](https://github.com/actions/python-versions/blob/main/README.md#building-installation-packages).
However, this build process can run into compatibility issues on macOS arm64 runners. The arm64 architecture is used in Apple's newer Mac models that use Apple Silicon processors, which are based on a different instruction set than the x86-64 processors used in older models.
Therefore, the built Python packages for versions less than 3.11 may trigger the issues like few modules missing on macOS arm64 runners. This is why the actions/setup-python repository does not support x64 packages for <Python 3.11 versions on macOS arm64 runners.
For Python versions 3.11 and onwards, the actions/setup-python repository uses the official macOS universal2 Python binaries from python.org, which are compatible with both x86-64 and arm64 architectures. These can be used on macOS arm64 runners without any issues.
For Arm64 platform, we use official macOS universal2 Python binaries and provide only versions which are provided by Python org.
Hence we are closing this issue as x64 packages for < python 3.11 from source will not be supported by macos arm64 runners. 
Please feel free to reach us needed to reopen this issue for more clarifications.

**Comment by ludwigschwardt** [comment]
No worries, it's a bit of a corner case anyway!
