### ISSUE TITLE
Python 3.5 setup fails with an invalid certificate when running pip

### ISSUE THREAD

**Issue by andy-maier** [actions/setup-python#866]
**Description:**

Python 3.5 setup fails with an invalid certificate when running pip.

This started happening a few days ago. 7 days ago it still worked.

From a today's run where it failed: https://github.com/zhmcclient/zhmc-ansible-modules/actions/runs/9076784995/job/24940262974
```
Run actions/setup-python@v5
  with:
    python-version: 3.5
    check-latest: false
    token: ***
    update-environment: true
    allow-prereleases: false
  env:
    PIP_DISABLE_PIP_VERSION_CHECK: 1
    PIP_NO_PYTHON_VERSION_WARNING: 1
Installed versions
  Version 3.5 was not found in the local cache
  Version 3.5 is available for downloading
  Download from "https://github.com/actions/python-versions/releases/download/3.5.10-90026/python-3.5.10-linux-20.04-x64.tar.gz"
  Extract downloaded archive
  /usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/bbd73505-bdd7-43f6-9be8-ea09e3ed6949 -f /home/runner/work/_temp/20ce11ed-ebf4-4b07-b07d-6c43d465aa62
  Execute installation script
  Check if Python hostedtoolcache folder exist...
  Create Python 3.5.10 folder
  Copy Python binaries to hostedtoolcache folder
  Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
  Upgrading PIP...
  Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages
  Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages
  Collecting pip
  Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:728) - skipping
  Error: Could not find a version that satisfies the requirement pip (from versions: )
  Error: No matching distribution found for pip
  Error: The process '/usr/bin/bash' failed with exit code 1
```

**Action version:**

v5

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Python 3.5

**Repro steps:**  

To reproduce, use the setup-python action with Python 3.5.

**Expected behavior:**

Python 3.5 should be installed as it was 1 week ago.

**Actual behavior:**

See description, above.

**Comment by joamag** [comment]
I'm also being able to repro this in a self hosted env

**Comment by aparnajyothi-y** [comment]
Hello @andy-maier, Thank you for creating this issue and we will look into it :)

**Comment by dirkf** [comment]
The Python 3.4.4 Windows MSI installation is also affected and also responds to the `PIP_TRUSTED_HOST` work-around. This is minimally documented at https://pip.pypa.io/en/latest/cli/pip/:
```
--trusted-host <hostname>

    Mark this host or host:port pair as trusted, even though it does not have valid or any HTTPS.

    (environment variable: PIP_TRUSTED_HOST)
```
Presumably pypi.org has reconfigured its servers with some new web-breaking security option so that older SSL implementations can't verify its certificate? If so the "temporary" work-around may be wrongly described.

**Comment by priya-kinthali** [comment]
Hello everyone 👋, 
This issue seems to be related to the inability of older versions of Python and pip to verify the SSL certificate provided by PyPI servers, likely due to recent updates in PyPI's SSL setup. Notably, Python 3.5 has reached its end of life and may not be able to verify the new certificate due to compatibility issues. 
However, please note that this problem doesn't directly fall within the scope of the 'actions/setup-python' repository, as it's more related to Python's interaction with PyPI, not the setup process itself.
A potential solution could be to upgrade to a newer versions of Python. If upgrading Python isn't feasible, please consider implementing the below workaround as suggested by @joamag .

```yaml
- uses: actions/setup-python@v5
  with:
    python-version: 3.5
  env:
    PIP_TRUSTED_HOST: "pypi.python.org pypi.org files.pythonhosted.org"  
```
If you have any concerns feel free to ping us. Thank you for your understanding and cooperation:)

**Comment by dirkf** [comment]
Since the point of the action is to install various versions of Python, end-of-life or not, you need to apply this workaround for the affected versions **within** the action itself.

**Comment by ShadowJonathan** [comment]
I agree, but adding these environment variables effectively ignores any SSL error, including MITM certificate mismatches. I feel like a `INSECURE_EOL_VERSION_OK: 1` (or similar) would be a better environment variable, *explicitly* acknowledging that EOL versions with security incompatibilities will be vulnerable to attacks, and that developers are okay with that (or have other security mitigations)

**Comment by priya-kinthali** [comment]
Thank you for your suggestions. Unfortunately, it's not feasible for us to incorporate the proposed changes directly into the `setup-python` action. For users operating with `EOL Python versions`, we kindly recommend implementing the proposed [workaround](https://github.com/actions/setup-python/issues/866#issuecomment-2154968862) within your respective workflows. For optimal security, please consider upgrading to a supported Python version. 
@andy-maier👋, as the issue appears to have been resolved with the suggested workaround, we are proceeding with closing the issue and appreciate your understanding and cooperation:)
Please feel free to reach us out incase of any other concerns.
