### ISSUE TITLE
Add Python 3.13.0rc1

### ISSUE THREAD

**Issue by jacobtylerwalls** [actions/setup-python#917]
**Description:**
Add Python 3.13.0rc1 (July 31, 2024) to 3.13-dev.

**Justification:**
As a library author about to declare 3.13 compatibility, I would like to continue testing against the latest 3.13 pre-releases. (I also have a 3.13-dev action that will continue to fail until I get an image of rc1 that fixes a regression in 3.13.0b4.)

**Are you willing to submit a PR?**

**Comment by neutrinoceros** [comment]
@jacobtylerwalls 3.13.0rc1 will be available once the following PR is merged: https://github.com/actions/python-versions/pull/300

**Comment by edgarrmondragon** [comment]
This can probably be closed. Python 3.13.0rc1 is now available :)

**Comment by dbarnett** [comment]
Usage question: is there any way to specify "latest 3.13 version" instead of locking in the full version number (right now "3.13.0-rc.2")?

I tried just specifying "3.13" or "3.13-rc" (since just "3.12" does work) but got "not found in the local cache" errors whatever I tried. Couldn't understand from reading the error and skimming https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json why a "3.12" alias would work but not those...

**Comment by edgarrmondragon** [comment]
> Usage question: is there any way to specify "latest 3.13 version" instead of locking in the full version number (right now "3.13.0-rc.2")?
> 
> I tried just specifying "3.13" or "3.13-rc" (since just "3.12" does work) but got "not found in the local cache" errors whatever I tried. Couldn't understand from reading the error and skimming https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json why a "3.12" alias would work but not those...

Have you tried with `3.13-dev`?

**Comment by dbarnett** [comment]
Thanks! No, I hadn't, but that seems to work.

That resolves my issue, but do consider making it easier to find those "-dev" aliases. They don't seem to exist explicitly in the manifest files or in any obvious version lists I can find.
