### ISSUE TITLE
PyPy 3.9-nightly is less than a day old, but PyPy 3.10-nightly is a week old

### ISSUE THREAD

**Issue by nedbat** [actions/setup-python#918]
**Description:**
I'm running the coverage.py test suite on nightly builds of PyPy installed with setup-python.  I am adding a check of how recently they have been built:  https://github.com/nedbat/coveragepy/actions/runs/10265368769.  The 3.9 build says "days since built: 0", but 3.10 says "days since built: 7".  Why are they different? Shouldn't the 3.10 version also be built every day?

**Comment by aparnajyothi-y** [comment]
Hello @nedbat, Thank you for creating this issue and we will look into it :)

**Comment by nedbat** [comment]
For whatever reason, now PyPy 3.9 is one day old, and PyPy 3.10 is two days old, so something is fixed?

**Comment by aparnajyothi-y** [comment]
Hello @nedbat, Thank you for the confirmation. It seems like the nightly build schedule for PyPy 3.9 and 3.10 has normalized, and they are now being built more regularly. However, if there are still discrepancies, it might be due to occasional build failures or delays in the build process from the official PyPy team.

setup-python is responsible for installing and managing Python versions, including PyPy. It handles fetching specific versions, ensuring they match the required formats, and installing them on GitHub Actions runners.
If PyPy 3.9-nightly is less than a day old and PyPy 3.10-nightly is a week old, setup-python would handle these versions based on the latest available builds and their respective versions, ensuring they are fetched and set up correctly.

Please feel free to reach us in case of any further concerns or information needed.

**Comment by aparnajyothi-y** [comment]
Hello @nedbat, Please let us know if any concerns/clarifications on the above information.

**Comment by nedbat** [comment]
It looks like this is fixed, thanks!
