### ISSUE TITLE
Permission denied when using os: self-hosted

### ISSUE THREAD

**Issue by cikichen** [actions/setup-python#937]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [✅] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ✅] Self-hosted

**Tools version:**

actions/setup-python@v5
**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.
Permission denied when using os: self-hosted。However, using v3 works fine.
**Expected behavior:**
A description of what you expected to happen.
```
Download from "https://github.com/actions/python-versions/releases/download/3.11.3-4626642838/python-3.11.3-darwin-arm64.tar.gz"
  Extract downloaded archive
  /usr/bin/tar xz -C /Users/workspace/actions-runner/_work/_temp/d5d1c8f1-7d15-4014-8bd0-1dbfaee973fd -f /Users/workspace/actions-runner/_work/_temp/c42f84f1-b999-4f6d-91fe-06b626bd3619
  Execute installation script
  Check if Python hostedtoolcache folder exist...
  Creating Python hostedtoolcache folder...
  Error: mkdir: /Users/runner:
  Error: Permission denied
  Error: The process '/bin/bash' failed with exit code 1
```
**Actual behavior:**
A description of what is actually happening.

**Comment by mahalakshmi-rekadi** [comment]
Hello  @cikichen ,

The actions/setup-python action is designed to work in the predefined environment of GitHub-hosted runners, which include certain directory structures and user permissions.
According to the [advanced-usage.md](https://github.com/actions/setup-python/blob/2f078955e4d0f34cc7a8b0108b2eb7bbe154438e/docs/advanced-usage.md#macos), for macOS, the Python packages require installation in /Users/runner/hostedtoolcache due to their non-relocatable nature.
To allow the action to have write access to the /Users/runner/hostedtoolcache directory, you can use the following commands:

1. Create the directory if it doesn't exist:
    mkdir -p /Users/runner/hostedtoolcache
2. Change the ownership of the directory to the runner's user and group:
    chown: sudo chown runner-user:runner-group /Users/runner/hostedtoolcache

Please note that if your environment does not allow modification of user groups or touching files outside of the runner home directory, you might not be able to use this action as intended since it requires write access to /Users/runner/hostedtoolcache.
Hope this clarifies. Please feel free to reach out to us in case of any concerns.

**Comment by cikichen** [comment]
> Hello @cikichen ,
> 
> The actions/setup-python action is designed to work in the predefined environment of GitHub-hosted runners, which include certain directory structures and user permissions. According to the [advanced-usage.md](https://github.com/actions/setup-python/blob/2f078955e4d0f34cc7a8b0108b2eb7bbe154438e/docs/advanced-usage.md#macos), for macOS, the Python packages require installation in /Users/runner/hostedtoolcache due to their non-relocatable nature. To allow the action to have write access to the /Users/runner/hostedtoolcache directory, you can use the following commands:
> 
> 1. Create the directory if it doesn't exist:
>    mkdir -p /Users/runner/hostedtoolcache
> 2. Change the ownership of the directory to the runner's user and group:
>    chown: sudo chown runner-user:runner-group /Users/runner/hostedtoolcache
> 
> Please note that if your environment does not allow modification of user groups or touching files outside of the runner home directory, you might not be able to use this action as intended since it requires write access to /Users/runner/hostedtoolcache. Hope this clarifies. Please feel free to reach out to us in case of any concerns.

Yes, it's because the v5 version has the directory fixed under the /Users folder. However, wouldn't it be better if we could follow the v3 version approach, where all directories are under the actions-runner folder specified by GitHub?

**Comment by mahalakshmi-rekadi** [comment]
Hello @cikichen,
Thank you for your feedback and for highlighting the differences between version 3 and version 5 of the actions/setup-python action.

Yes, the issue arises because v5 of actions/setup-python has a fixed directory structure under /Users/runner/hostedtoolcache, requiring write access. You can either:

1.Continue using v3, which places directories under the actions-runner folder specified by GitHub.
2.Adjust directory permissions to use v5.
3.Raise a feature request for custom installation paths in v5.

Hope this helps! Please feel free to reach out to us in case of any concerns.

**Comment by ironmanmarkyo** [comment]
@cikichen Hi. Did you find a solution to this problem?
