### ISSUE TITLE
Python 3.7 broken on macos-13 due to `ImportError: dlopen(...): Library not loaded: /usr/local/opt/zlib/lib/libz.1.dylib`

### ISSUE THREAD

**Issue by haampie** [actions/setup-python#964]
**Description:**

The `Python 3.7.17` binaries for `macos-13` on `x86-64` are broken: they depend on Homebrew's libz.1.dylib, but it's not installed by default. This probably should have been system zlib instead.

It causes failure of certain scripts, depending on import order, like this:

```  File "/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/base64.py", line 11, in <module>
    import binascii
ImportError: dlopen(/Users/runner/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/lib-dynload/binascii.cpython-37m-darwin.so, 0x0002): Library not loaded: /usr/local/opt/zlib/lib/libz.1.dylib
```

Indeed this Python library encodes a path to a non-existent `libz.1.dylib`:

```
$ wget -q https://github.com/actions/python-versions/releases/download/3.7.17-5356448435/python-3.7.17-darwin-x64.tar.gz                                                                                                                              

$ tar xf python-3.7.17-darwin-x64.tar.gz 

$ otool -L ./lib/python3.7/lib-dynload/binascii.cpython-37m-darwin.so
./lib/python3.7/lib-dynload/binascii.cpython-37m-darwin.so:
        /usr/local/opt/zlib/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.13)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)

$ file /usr/local/opt/zlib/lib/libz.1.dylib
/usr/local/opt/zlib/lib/libz.1.dylib: cannot open `/usr/local/opt/zlib/lib/libz.1.dylib' (No such file or directory)
```

I've seen this issue so far *only* with the latest Python 3.7 `3.7.17`, not with other Python versions. (I only checked the last 3.6 release: it correctly refers to system libz.1.dylib.)

---

The workaround is to `brew install zlib` before using Python from the `setup-python` action. But that is bizarre.

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.7.17

**Repro steps:**  
Haven't managed to get a small MWE yet: it is load order dependent, and you have to let python `import base64` before it has loaded system libz.1.dylib through another code path. I think the error triggers using multiprocessing in spawn mode.

**Expected behavior:**
Python loads libz.dylib from the system.

**Actual behavior:**
Python fails to load libz.dylib because it tries refers to a non-existing path `/usr/local/lib/*`

**Comment by haampie** [comment]
It seems like 3.7.16 is NOT affected by this issue:

```
$ otool -L ./lib/python3.7/lib-dynload/binascii.cpython-37m-darwin.so
./lib/python3.7/lib-dynload/binascii.cpython-37m-darwin.so:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

**Comment by priyagupta108** [comment]
Hi @haampie 👋,
Thank you for your report. We'll investigate the issue and get back to you with the details!

**Comment by aparnajyothi-y** [comment]
Hello, Thank you of once again for creating this issue. We have tested it on macOS-13 and were unable to reproduce the issue from our end. Please find the screenshots for reference. If the issue persists on your end with macOS-13, kindly provide a repro link so we can assist you further.

Feel free to reach out if you need further clarifications.

**Comment by haampie** [comment]
Here's a similar minimal working example with readline:

https://github.com/haampie/macos-13-setup-python-repro

fails on 3.7.17, fine on 3.7.16

The same thing happens with libz under certain circumstances.

**Comment by aparnajyothi-y** [comment]
Hello @haampie, Thank you for providing the repro links. Upon investigation, the issue with Python 3.7.17 on macOS 13 is caused by a dependency issue related to zlib. Python 3.7.17 was compiled with a dependency on Homebrew’s zlib, but macOS 13 no longer ships with zlib by default. As a result, Python fails when attempting to load libz.1.dylib.

This issue does not occur with Python 3.7.16 because it does not rely on Homebrew's zlib. Instead, Python 3.7.16 is likely using the system’s libSystem library, which includes zlib by default. As a result, Python 3.7.16 can use the system version of zlib without issue, thereby avoiding the problem you're encountering on macOS 13.

Since Python 3.7.17 is EOL (End of Life) and no longer receives updates, we recommend upgrading to a newer version of Python that does not rely on these missing dependencies and is fully compatible with macOS 13.

Please let us know if you have any further questions or support needed.

**Comment by haampie** [comment]
That was all what I told you when I opened the issue.

I don't see the point of setup-python if old versions are broken.

EOL does not mean there are suddenly no users.

**Comment by aparnajyothi-y** [comment]
Hello @haampie, Thank you for providing the repro links. Upon investigation, we recommend a workaround to install the modules like bzip2, readline, and ncurses using Homebrew, which will allow Python 3.7.17 to build and run without issues. This workaround addresses the missing zlib dependency, which is no longer bundled with macOS 13 and later. Since Python 3.7.17 relies on these libraries, it is better to install them manually. From Python 3.9 onward, this issue no longer occurs, as newer versions of Python handle dependencies differently. Therefore, updating the runner images with these missing modules may not be necessary at this time.

Here’s the step to add to your GitHub Actions workflow:

yaml
Copy code
- name: Install Homebrew and dependencies
  run: |
    /bin/bash -c ""$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)""
    brew install bzip2 readline ncurses

Please let us know if you need further assistance!

**Comment by aparnajyothi-y** [comment]
Hello @haampie, Please confirm if the workaround provided has temporarily resolved the issue.

We will keep a note of the proposed solution for future reference, which involves patching the binaries using install_name_tool to address the missing zlib dependency. Since macOS 13 and later no longer bundle this dependency, we recommend installing it manually, especially given that Python 3.7.17 relies on these libraries. Starting with Python 3.9, this issue no longer occurs, as newer Python versions handle dependencies differently. Therefore, updating the runner images with these missing modules may not be necessary at this time.

Please feel free to reach us if you have any further concerns or need additional clarification.

**Comment by haampie** [comment]
It's funny cause I've posted both the cause of the issue as well as a workaround when opening the issue.

My request was to have it fixed properly. But since that's not happening I'll close this.
