### ISSUE TITLE
Add/support windows-aarch64

### ISSUE THREAD

**Issue by ritchie46** [actions/setup-python#976]
I am not sure if this is a feature request or a bug report. But when we wanted to release a new binary for windows with aarch64 support upstream in Polars, we got a failure in the `setup-python` step for that architecture.

```
Run actions/setup-python@v5
Installed versions
  Version 3.9 was not found in the local cache
  Error: The version '3.9' with architecture 'arm64' was not found for Windows Enterprise.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

The full logs are here: https://github.com/pola-rs/polars/actions/runs/12012857821/job/33485043287

Would be a great if windows + aarch64 had support.

**Comment by priyagupta108** [comment]
Hello @ritchie46 👋, Thank you for your report. 
For Windows, the official Python executables are simply downloaded from [python.org](https://www.python.org/ftp/python/). Unfortunately, binary installers are not available for arm64 Windows for the 3.9 versions. You can verify this by visiting [Python Downloads for Windows](https://www.python.org/downloads/windows) and checking the releases that have binary installers for Windows arm64.
 You may consider using a different version of Python that has binary installers available for this architecture.
Hope this clarifies!

**Comment by priyagupta108** [comment]
Hi @ritchie46,
As mentioned earlier, the official Python executables for Windows do not include binary installers for arm64 in the 3.9 versions. Given this limitation, it is recommended to use a different Python version that supports arm64 for Windows.

Since there are no further actions we can take from our end, we are closing this issue. If you have any other questions or need further assistance, please feel free to contact us. Thank You!

**Comment by ritchie46** [comment]
Thanks, take a look with a different version!
